DECLARE
BEGIN
EXECUTE IMMEDIATE
'create table PLATFORM_STCK_BKP_&1 as select * from PLATFORM_STCK;
create table PLATFORM_DTL_BKP_&1 as select * from PLATFORM_DTL;
create table CONNECTION_DETAILS_&1 as select * from CONNECTION_DETAILS;
create table PROP_CNTNT_BKP_&1 as select * from PROP_CNTNT;
create table OPT_TAB_COL_BKP_&1 as select * from OPT_TAB_COL;
create table SRC_BKP_&1 as select * from SRC ;
create table CLNT_BKP_&1 as select * from CLNT';

EXECUTE IMMEDIATE	

--PLATFORM_STCK
---------------------
INSERT INTO PLATFORM_STCK VALUES(&16, ''&2'', SYSDATE, SYSDATE, NULL);
commit;
-- Platform_ID

--PLATFORM_DTL
---------------------
--- Connection id 1 is for ODCONIFG, CKA database details which is common for all clients therefore, we need to map connection id to platform id 25 as well
INSERT INTO PLATFORM_DTL(PLTFM_ID, CONNECTION_ID) VALUES(&16,1);
commit;

---------below connection ids are new for platform id 25.. the connection ids starting with plaform ids + sequence number threfore its like &17,251,252,253 etc..
--We need following conneciton ids
--&17 = with all CIF databases , id and password (AODR1Q_LC2_TLOG_ODS, AODR1Q_LC2_TLOG_STG,"ADMIN.AODR1Q_CKR_ADV" (This is common one should be used as advised by Bala)
-- (for ODS, we need only 1 new connection id. For FS, we may need few more but these will be taken care by FS team)
INSERT INTO PLATFORM_DTL(PLTFM_ID, CONNECTION_ID) VALUES(&16,&17);

commit;

-- CONNECTION DTL 
---------------------
--Connection id &17
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_STG_SVR'',''&10'');
commit;
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_STG_UID'',''&11'');
commit;
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_STG_DB'',''&12'');
commit;
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_STG_PW'',''&13'');
commit;
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_ODS_DB'',''&14'');
commit;
INSERT INTO CONNECTION_DETAILS(CONNECTION_ID, PARAMETER_NAME, PARAMETER_VALUE) VALUES(&17,''NTZ_ODS_CKR_DB'',''&15'');
commit;';
EXECUTE IMMEDIATE
'-- PROP_CNTNT
 ------------------------
 -- Hope this creates the "LOYALTY_tlog_properties.ksh" file in SQA Unix environment? 
 
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#!/bin/sh'',1);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,2);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Netezza Tlog Staging Database'',3);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_STG_HOST="${NTZ_ODS_STG_SVR}"'',4);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_STG_DB="${NTZ_ODS_STG_DB}"'',5);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_STG_USER="${NTZ_ODS_STG_UID}"'',6);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_STG_PASS="${NTZ_ODS_STG_PW}"'',7);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,8);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Netezza Tlog Staging Database'',9);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_ODS_HOST="${NTZ_ODS_STG_SVR}"'',10);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_ODS_DB="${NTZ_ODS_ODS_DB}"'',11);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_ODS_USER="${NTZ_ODS_STG_UID}"'',12);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_ODS_PASS="${NTZ_ODS_STG_PW}"'',13);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,14);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Netezza Tlog Staging Database'',15);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_CKR_HOST="${NTZ_ODS_STG_SVR}"'',16);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_CKR_DB="${NTZ_ODS_CKR_DB}"'',17);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_CKR_USER="${NTZ_ODS_STG_UID}"'',18);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_CKR_PASS="${NTZ_ODS_STG_PW}"'',19);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,20);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Oracle ABC Database'',21);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ABC_UNM=${ORA_CMI_ABC_SCHEMA}'',22);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ABC_PWD=${ORA_CMI_ABC_PW}'',23);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ABC_DBNM=${ORA_CMI_DB}'',24);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ABC_DB_NM=${ORA_CMI_ABC_SCHEMA}'',25);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,26);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Oracle Configuration Database'',27);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CFG_DB_USR=${ORA_CMI_CONFIG_SCHEMA}'',28);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CFG_DB_PWD=${ORA_CMI_CONFIG_PW}'',29);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CFG_DB_SRVR=${ORA_CMI_DB}'',30);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CFG_DB_NM=${ORA_CMI_CONFIG_SCHEMA}'',31);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,32);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#DIMENSION LIST FOR PULL NATURAL KEYS'',33);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DIMENSION_LIST="''PRODUCT'',''PERIOD'',''STORE'',''BASKET'',''HOUSEHOLD'',''PERSON'',''IDENTIFYING_CARD'',''LANE''"'',34);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,35);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Application Specific'',36);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export REQUESTER_NAME=TLOGAPP'',37);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,38);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export FL_WTCH_RTRN_CD=99'',39);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CHK_TOT_FLS_RTRN_CD=199'',40);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,41);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Source tables'',42);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ABC_HIGH_LOW=ABC_HIGH_LOW'',43);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,44);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#ABC Tables'',45);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ODABC_DB=${ABC_UNM}'',46);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export BATCH_TRCK=${ODABC_DB}.BATCH_TRCK'',47);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export FL_RGSTR_TBL=${ODABC_DB}.FL_RGSTR'',48);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,49);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Configuration Tables'',50);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CONFIG_DB=${CFG_DB_USR}'',51);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SBJ_AREA_TBL=${CONFIG_DB}.SBJ_AREA'',52);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SRC=${CONFIG_DB}.SRC'',53);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DIM=${CONFIG_DB}.DIM'',54);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CUST_ADAPT_TBL=${CONFIG_DB}.CUST_ADAPT'',55);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export OBJ_GRP_TBL=${CONFIG_DB}.OBJ_GRP'',56);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#########CKA IDLE TIME'',57);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,58);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_Resv_IdleTm=15 seconds'',59);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_Resv_IdleLimit=6'',60);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,61);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Directory paths'',62);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export APPHOME=$APP_HOME'',63);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CODEDIR=${APPHOME}/code'',64);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export BINDIR=${CODEDIR}/bin'',65);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CUST_ADPTR_BINDIR=${BINDIR}/cust_adapter'',66);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TRIP_CUST_ADPTR_BINDIR=${BINDIR}/trip_cust_adapter'',67);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export PROPDIR=${CODEDIR}/properties'',68);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ORASQL=${CODEDIR}/sql'',69);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export LOGDIR=${APPHOME}/logs'',70);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export WRKDIR=${APPHOME}/working'',71);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SQLDIR=${WRKDIR}/sql'',72);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TEMPDIR=${WRKDIR}/tmp'',73);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export COMMON_DIR=${APPHOME}/code/bin'',74);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATADIR=${APPHOME}/data'',75);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export OUTPUTDIR=${DATADIR}/outputs'',76);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export INPUTDIR=${DATADIR}/inputs'',77);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export STGDIR=${OUTPUTDIR}/staging'',78);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export LOADDIR=${OUTPUTDIR}/loading'',79);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CONFIG_DATA=${INPUTDIR}/config'',80);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export INITLOAD_DIR=${INPUTDIR}/init_load'',81);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export LANDING_DIR=${INPUTDIR}/landing'',82);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,83);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#CKA Meta and Data file Directories'',84);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_APPHOME=${DSG_CKA_APP_PATH}'',85);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_BIN=${CKA_APPHOME}/code/bin'',86);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAOUT_DIR=${CKA_APPHOME}/data/inputs/xml'',87);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAIN_DIR=${CKA_APPHOME}/data/outputs/xml'',88);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,89);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Local Meta and Data file Directories'',90);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAINLOCAL_DIR=${INPUTDIR}/xml'',91);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAOUTLOCAL_DIR=${OUTPUTDIR}/xml'',92);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,93);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAINARCH_DIR=${XMLINLOCAL_DIR}/archive'',94);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAOUTARCH_DIR=${XMLOUTLOCAL_DIR}/archive'',95);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAOUT_REJ_DIR=${XMLOUTLOCAL_DIR}/rejects'',96);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export DATAIN_REJ_DIR=${XMLINLOCAL_DIR}/rejects'',97);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,98);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Local XML Directories'',99);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLINLOCAL_DIR=${INPUTDIR}/xml'',100);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLOUTLOCAL_DIR=${OUTPUTDIR}/xml'',101);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,102);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLINARCH_DIR=${XMLINLOCAL_DIR}/archive'',103);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLOUTARCH_DIR=${XMLOUTLOCAL_DIR}/archive'',104);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLOUT_REJ_DIR=${XMLOUTLOCAL_DIR}/rejects'',105);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLIN_REJ_DIR=${XMLINLOCAL_DIR}/rejects'',106);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,107);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#CKA XML Directories'',108);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_APPHOME=${DSG_CKA_APP_PATH}'',109);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_BIN=${CKA_APPHOME}/code/bin'',110);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLOUT_DIR=${CKA_APPHOME}/data/inputs/xml'',111);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export XMLIN_DIR=${CKA_APPHOME}/data/outputs/xml'',112);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,113);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Common Process'',114);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CMMN_PRCS_FUNCDIR=${REL_HOME}/common_processes/code/functions'',115);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CMMN_PRCS_PROPDIR=${REL_HOME}/common_processes/code/properties'',116);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,117);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Dim Sourcing TEMP*****************'',118);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''##export DSMNTR_HOME=${REL_HOME}/dimension_sourcing'',119);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,120);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Keying Properties'',121);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ARCHV_DAYS=7'',122);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,123);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#DSjob directory'',124);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_DSPROJNAME=${DSG_TLOG_PROJ}'',125);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,126);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Misc properties'',127);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#xport MAIL_RECIPIENT="udhayapriya.maruthaiyan.ap@nielsen.com"'',128);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#export MAIL_RECIPIENT="jayasubha.kanakaraj.ap@nielsen.com"'',129);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export MAIL_RECIPIENT=""'',130);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,131);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#ODS Properties'',132);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ODS_SQL_CONFIG=${PROPDIR}/ods_sql_properties.conf'',133);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export LOAD_PARSER=${BINDIR}/tlog_parse_sqlconf.awk'',134);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export TLOG_HISTORY=LOAD_HIST'',135);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export VAL_PARSER=${BINDIR}/tlog_parse_val.awk'',136);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export ODS_BKP_TRSHLD=7'',137);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export WEEKLY_BKP_DAY=3,4,5'',138);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export WBKP_THRESHOLD=7'',139);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,140);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Combine Data Restatement Properties'',141);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_BAS="BAR"'',142);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_ITM="ITR"'',143);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_BNI="BNR"'',144);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_BDI="BRS"'',145);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_BID="BIR"'',146);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#export RESTMT_AREA_AGP="AGR"'',147);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_AGP="RGP"'',148);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_HHA="HAR"'',149);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RESTMT_AREA_HHS="HHR"'',150);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,151);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,152);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################################'',153);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''# Variables added temporarily for IDC Keying workaround'',154);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''# To be removed once workaround is no longer needed'',155);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################################'',156);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#Oracle CKA Database'',157);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_UNM=${ORA_CKAADV_CKAADV_SCHEMA}'',158);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_PWD=${ORA_CKAADV_CKAADV_PW}'',159);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_DBNM=${ORA_CKAADV_DB}'',160);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CKA_DB_NM=${ORA_CKAADV_CKAADV_SCHEMA}'',161);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,162);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,163);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''########################################'',164);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''# Variables for Historical Load Wrapper'',165);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''########################################'',166);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export BATCH_THRSHLD=5'',167);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export MANIFEST_WAIT=600'',168);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export BATCH_WAIT=600'',169);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,170);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''########################################'',171);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''# Process Event Servirities'',172);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''########################################'',173);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SC_DEBUG="-1"'',174);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SC_INFO="0"'',175);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SC_WARNING="1"'',176);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SC_ERROR="2"'',177);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SC_FATAL="FATAL"'',178);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,179);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,180);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################'',181);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#SAS Extract Variables'',182);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################'',183);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export SAS_EXTRACT_OUTPUT_DIR=/ido/od251dev/data/nsk'',184);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export EMAIL_IDS="Robert.Moore.ap@nielsen.com;Varaprasad.Kadali.ap@nielsen.com"'',185);
----------------------------Change the email id to Laxmi or ODS group id----------------------
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export RMT_ENV_ID="301"'',186);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,187);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################'',188);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#2.9 Changes'',189);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#######################################'',190);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export GRP_COMPLTNESS_DATLMT=2'',191);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export CHK_TOT_DAYLMT=10'',192);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,193);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''####################################3'',194);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''#nzload changes'',195);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''####################################'',196);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export MAX_ERR=1'',197);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',null,198);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''####################################'',199);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''# FILE WATCHER VARIABLES'',200);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''####################################'',201);
commit;
Insert into PROP_CNTNT (SOURCE_ID,PLATFORM_ID,PROP_FL_NM,PROP_FL_CNTNT,LINE_NUM) values (&4,&16,''LOYALTY_tlog_properties.ksh'',''export FL_STBLIZE_CNT=3'',202);
commit;

-- OPT_TAB_COL
--------------------------
-- Seriously what is this table do?
-- do we have default entries like below for all clients?

/*
Insert into OPT_TAB_COL (SRC_ID,SBJ_AREA_CD,COL_NM) values (&4,''ITM'',''Original_Price'');
Insert into OPT_TAB_COL (SRC_ID,SBJ_AREA_CD,COL_NM) values (&4,''PRO'',''Multipack_Quantity'');
Insert into OPT_TAB_COL (SRC_ID,SBJ_AREA_CD,COL_NM) values (&4,''PRO'',''Unit_Of_Measure'');
commit;
----Ask Bala to confirm these above columns later...
*/

--SRC and CLNT for Casino
insert into SRC (SRC_ID,SRC_CD,SRC_DSC,CKA_SUB_ID,CKA_SUB_NM,CRT_DT,LST_UPD_DT,LST_UPD_USR,SRC_STS) values (&4,''&2'',''&3'',&6,''&5'',SYSDATE,SYSDATE,''LCRODCONFIGQ'',''I'');
commit;

insert into CLNT (CLNT_ID,CLNT_CD,CLNT_DSC,CRT_DT,LST_UPD_DT,LST_UPD_USR) values (&9,''&7'',''&8'',SYSDATE,SYSDATE,''LCRODCONFIGQ'');
commit;';
END;
/