DROP TABLE CUST_ADAPT CASCADE CONSTRAINTS;
DROP TABLE DIM CASCADE CONSTRAINTS;
DROP TABLE OBJ CASCADE CONSTRAINTS;
DROP TABLE OBJ_GRP CASCADE CONSTRAINTS;
DROP TABLE OBJ_PRCS_EXCPN CASCADE CONSTRAINTS;
DROP TABLE PRCS_CONF CASCADE CONSTRAINTS;
DROP TABLE SBJ_AREA CASCADE CONSTRAINTS;
DROP TABLE SRVC_ORCH CASCADE CONSTRAINTS;
DROP TABLE STD_FMT_META_DTA CASCADE CONSTRAINTS;
DROP TABLE SUB_DIM_KEY CASCADE CONSTRAINTS;



-- 
-- TABLE: CUST_ADAPT 
--

CREATE TABLE CUST_ADAPT(
    CUST_ADAPT_ID            NUMBER(10, 0)    NOT NULL,
    CUST_ADAPT_CD            VARCHAR2(30)     NOT NULL,
    OBJ_GRP_ID               NUMBER(10, 0),
    SRC_ID                   NUMBER(10, 0),
    CUST_ADAPT_DSC           VARCHAR2(100),
    CUST_ADAPT_SCRPT         VARCHAR2(100),
    CUST_ADAPT_SCRPT_PARM    VARCHAR2(100),
    CUST_ADAPT_OUT_PATH      VARCHAR2(100),
    CUST_ADAPT_CMD           VARCHAR2(700),
    CRT_DT                   DATE             DEFAULT SYSDATE,
    LST_UPD_DT               DATE             DEFAULT SYSDATE,
    LST_UPD_USR              VARCHAR2(30)
);

-- 
-- TABLE: DIM 
--

CREATE TABLE DIM(
    DIM_ID         NUMBER(10, 0)    NOT NULL,
    DIM_CD         VARCHAR2(10),
    DIM_NM         VARCHAR2(30),
    CKA_DIM_ID     NUMBER(10, 0),
    CKA_DIM_NM     VARCHAR2(30),
    CRT_DT         DATE             DEFAULT SYSDATE,
    LST_UPD_DT     DATE             DEFAULT SYSDATE,
    LST_UPD_USR    VARCHAR2(30)
);

-- 
-- TABLE: OBJ 
--

CREATE TABLE OBJ(
    OBJ_FL_ID             NUMBER(18, 0)    NOT NULL,
    SBJ_AREA_ID           NUMBER(10, 0),
    SRC_ID                NUMBER(10, 0),
    OBJ_GRP_CD            VARCHAR2(10),
    OBJ_FL_NM             VARCHAR2(75),
    OBJ_FL_TYP            VARCHAR2(30),
    OBJ_FL_MODE           VARCHAR2(20),
    OBJ_FL_NM_CNVN_FLG    CHAR(1),
    OBJ_PRNT_OBJ_ID       NUMBER(18, 0),
    OBJ_MSK_STRT          NUMBER(4, 0),
    OBJ_MSK_END           NUMBER(4, 0),
    OBJ_CMPRSN_FLG        CHAR(1),
    OBJ_CMPRSN_TYP        VARCHAR2(10),
    OBJ_UNCMPRS_CMD       VARCHAR2(255),
    OBJ_META_FLG          CHAR(1),
    OBJ_HDR_FLG           CHAR(1),
    OBJ_HDR_CNT           NUMBER(2, 0),
    OBJ_FLD_SEP           VARCHAR2(5),
    OBJ_TOT_FL            NUMBER(6, 0),
    OBJ_FL_PRCS_CNt       NUMBER(6, 0),
    OBJ_FL_MRG_FLG        CHAR(1),
    OBJ_MRG_CNT           NUMBER(6, 0),
    OBJ_ARCHV_FLG         CHAR(10),
    OBJ_EXP_TM            VARCHAR2(10),
    OBJ_ELPSD_TM          VARCHAR2(10),
    OBJ_FPRNT_PRD         NUMBER(3, 0),
    EXCPN_FLG             CHAR(1),
	CLNT_ID               NUMBER(10,0),
    CLNT_FLG              CHAR(1)          DEFAULT 'N',
    CRT_DT                DATE             DEFAULT SYSDATE,
    LST_UPD_DT            DATE             DEFAULT SYSDATE,
    LST_UPD_USR           VARCHAR2(30)
);

-- 
-- TABLE: OBJ_GRP 
--

CREATE TABLE OBJ_GRP(
    OBJ_GRP_ID         NUMBER(10, 0)    NOT NULL,
    OBJ_GRP_CD         VARCHAR2(10),
    OBJ_GRP_DSC        VARCHAR2(30),
    SRC_ID             NUMBER(10, 0),
    OBJ_LOAD_FL_CNT    NUMBER(20, 0),
    APP_ID 			   VARCHAR2(10),
    CRT_DT             DATE             DEFAULT SYSDATE,
    LST_UPD_DT         DATE             DEFAULT SYSDATE,
    LST_UPD_USR        VARCHAR2(30)
);

-- 
-- TABLE: OBJ_PRCS_EXCPN 
--

CREATE TABLE OBJ_PRCS_EXCPN(
    PRCS_ID        NUMBER(10, 0)    NOT NULL,
    PRCS_CD        VARCHAR2(30)     NOT NULL,
    OBJ_FL_ID      NUMBER(18, 0),
    SRC_ID         NUMBER(10, 0),
    PRCS_NM        VARCHAR2(100),
    PRCS_FLG       VARCHAR2(10),
    CRT_DT         DATE             DEFAULT SYSDATE,
    LST_UPD_DT     DATE             DEFAULT SYSDATE,
    LST_UPD_USR    VARCHAR2(30)
);

-- 
-- TABLE: PRCS_CONF 
--

CREATE TABLE PRCS_CONF(
    PRCS_CONF_ID             NUMBER(10, 0)    NOT NULL,
    SRC_ID                   NUMBER(10, 0),
    PRCS_DBG_FLG             CHAR(1),
    PRCS_MNFST_TRSHLD_CYC    NUMBER(9, 0),
    CRT_DT                   DATE             DEFAULT SYSDATE,
    LST_UPD_DT               DATE             DEFAULT SYSDATE,
    LST_UPD_USR              VARCHAR2(30)
);

-- 
-- TABLE: SBJ_AREA 
--

CREATE TABLE SBJ_AREA(
    SBJ_AREA_ID            NUMBER(10, 0)    NOT NULL,
    SRC_ID                 NUMBER(10, 0),
    OBJ_GRP_ID             NUMBER(10, 0),
    SBJ_AREA_CD            VARCHAR2(10),
    SBJ_AREA_DSC           VARCHAR2(100),
    RESTATE_FLG            CHAR(10),
    RESTATE_SBJ_AREA_CD    VARCHAR2(10),
    SBJ_PASS_TRSHLD_PCT    NUMBER(3, 0),
    NEED_NEW_KEY           CHAR(1),
    NEED_PARK_FLG 		   CHAR(1),
    CRT_DT                 DATE             DEFAULT SYSDATE,
    LST_UPD_DT             DATE             DEFAULT SYSDATE,
    LST_UPD_USR            VARCHAR2(30)
);

-- 
-- TABLE: SRVC_ORCH 
--

CREATE TABLE SRVC_ORCH(
    SRVC_ORCH_ID          NUMBER(10, 0)    NOT NULL,
    SRC_ID                NUMBER(10, 0),
    CURR_SRVC_ID          VARCHAR2(50),
    NEXT_SRVC_ID          VARCHAR2(50),
    FORK_ID               NUMBER(10, 0),
    SCRPT_NM              VARCHAR2(100),
    NEXT_MSG_QUE          VARCHAR2(255),
    NEXT_SRVC_PRIORITY    NUMBER(10, 0),
    SKIP_NEXT_SRVC        VARCHAR2(10),
    TIMEOUT_MTS           NUMBER(5, 0),
    EFF_STRT_DT           DATE,
    EFF_END_DT            DATE,
    CRT_DT                DATE             DEFAULT SYSDATE,
    LST_UPD_DT            DATE             DEFAULT SYSDATE,
    LST_UPD_USR           VARCHAR2(30)
);

-- 
-- TABLE: STD_FMT_META_DTA 
--

CREATE TABLE STD_FMT_META_DTA(
    STD_FMT_META_ID    NUMBER(10, 0)    NOT NULL,
    SBJ_AREA_CD        VARCHAR2(10)     NOT NULL,
    TAB_NM             VARCHAR2(30)     NOT NULL,
    LOG_COL_NM         VARCHAR2(50),
    PHY_COL_NM         VARCHAR2(30)     NOT NULL,
    COL_DTA_TYP        VARCHAR2(20),
    NULL_OPT           VARCHAR2(20),
    KEEP_FLG           CHAR(1),
    DROP_FLG           CHAR(1),
    ISNIELSEN_KEY      CHAR(1),
    IS_ODS_COMP_KEY    CHAR(1),
    COLUMN_ORDER       INTEGER,
    CRT_DT             DATE             DEFAULT SYSDATE,
    LST_UPD_DT         DATE             DEFAULT SYSDATE,
    LST_UPD_USR        VARCHAR2(30)
);

-- 
-- TABLE: SUB_DIM_KEY
--

Create table SUB_DIM_KEY 
(
SBJ_AREA_ID NUMBER(10) NOT NULL,
SRC_ID NUMBER(10),
SBJ_AREA_CD VARCHAR2(10),
DIM_NM VARCHAR2(10),
NEED_NEW_KEY  CHAR(1),
CRT_DT  DATE  DEFAULT SYSDATE,
LST_UPD_DT   DATE  DEFAULT SYSDATE,
LST_UPD_USR  VARCHAR2(30)
);

-- run config script

GRANT SELECT ON OBJ TO LCRODABCQ ;
GRANT SELECT ON OBJ_GRP TO LCRODABCQ ;
GRANT SELECT ON PRCS_CONF TO LCRODABCQ ;
GRANT SELECT ON SBJ_AREA TO LCRODABCQ ;
GRANT SELECT ON SRC TO LCRODABCQ ;
GRANT SELECT ON DIM TO LCRODABCQ ;
GRANT SELECT ON STD_FMT_META_DTA TO LCRODABCQ;
GRANT SELECT ON SRVC_ORCH TO LCRODABCQ;
GRANT SELECT ON CUST_ADAPT TO LCRODABCQ;
GRANT SELECT ON OBJ_PRCS_EXCPN TO LCRODABCQ;









----------Drop and Re-create sequences

DROP SEQUENCE SEQ_CUST_ADAPT_ID;
DROP SEQUENCE SEQ_DIM_ID
DROP SEQUENCE SEQ_OBJ_FL_ID;
DROP SEQUENCE SEQ_OBJ_GRP_ID;
DROP SEQUENCE SEQ_OBJ_PRCS_EXCPN_ID;
DROP SEQUENCE SEQ_PRCS_CONF_ID;
DROP SEQUENCE SEQ_SBJ_AREA_ID;
DROP SEQUENCE SEQ_SRVC_ORCH_ID;


---- Configu load scripts drop the sequence SEQ_STD_FMT_META_ID(for STD_FMT_META_DTA)  and recreate therefore not required to be dropped manually.
--- SUB_DIM_KEY table load does not use sequence.


CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_CUST_ADAPT_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_DIM_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_OBJ_FL_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_OBJ_GRP_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_OBJ_PRCS_EXCPN_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
        
CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_PRCS_CONF_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
        
CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_SBJ_AREA_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  "LCRODCONFIGQ"."SEQ_SRVC_ORCH_ID"  
       MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
        



GRANT USAGE ON SEQUENCE SEQ_CUST_ADAPT_ID       TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_DIM_ID              TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_OBJ_FL_ID           TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_OBJ_GRP_ID          TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_OBJ_PRCS_EXCPN_ID   TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_PRCS_CONF_ID        TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_SBJ_AREA_ID         TO LCRODABCQ ;
GRANT USAGE ON SEQUENCE SEQ_SRVC_ORCH_ID        TO LCRODABCQ ;
;