DECLARE
	v_stmt_drop1 VARCHAR2(500) := 'DROP TABLE PLATFORM_STCK_BKP_&1';
	v_stmt_drop2 VARCHAR2(500) := 'DROP TABLE PLATFORM_DTL_BKP_&1';
	v_stmt_drop3 VARCHAR2(500) := 'DROP TABLE CONNECTION_DETAILS_&1';
	v_stmt_drop4 VARCHAR2(500) := 'DROP TABLE PROP_CNTNT_BKP_&1';
	v_stmt_drop5 VARCHAR2(500) := 'DROP TABLE OPT_TAB_COL_BKP_&1';
	v_stmt_drop6 VARCHAR2(500) := 'DROP TABLE SRC_BKP_&1';
	v_stmt_drop7 VARCHAR2(500) := 'DROP TABLE CLNT_BKP_&1';

BEGIN
	EXECUTE IMMEDIATE v_stmt_drop1;
	EXECUTE IMMEDIATE v_stmt_drop2;	
	EXECUTE IMMEDIATE v_stmt_drop3;
	EXECUTE IMMEDIATE v_stmt_drop4;
	EXECUTE IMMEDIATE v_stmt_drop5;
	EXECUTE IMMEDIATE v_stmt_drop6;
	EXECUTE IMMEDIATE v_stmt_drop7;
	COMMIT;

END;
/	


